# -*- coding: utf-8 -*-
"""belgian.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18YNo0CUwZjMSc4YbrjR9XQ_ew3vDr8hD
"""

# !pip install playwright pandas openpyxl
# !playwright install chromium
# !pip install nest_asyncio
#import nest_asyncio


import asyncio, re, os, json
import pandas as pd
from playwright.async_api import async_playwright
from datetime import datetime

today_date = datetime.now().strftime("%Y%m%d")
BASE_URL = "https://pharmastatus.be/human/medical-products"
FOLDER_PATH = r"C:\Users\HP\Desktop"  #r"C:\Users\curra\OneDrive\Desktop\Personal\PS\Data\belgian" # Change this if needed

LL_FILENAME = os.path.join(FOLDER_PATH, f"Belgium Output LL {today_date}.xlsx")
EN_FILENAME = os.path.join(FOLDER_PATH, f"Belgium Output EN {today_date}.xlsx")
BUGS_FILENAME = os.path.join(FOLDER_PATH, f"Belgium Bugs {today_date}.xlsx")

FIELD_HEADERS = [
    "Country", "ATC3 code", "ATC4 code", "Molecule", "Product Name",
    "Product Strength", "Product Pack Size", "Corporation", "Shortage Status",
    "Date reported", "Start date", "End date", "Date last updated", "Relevant unit",
    "Alternatives available", "Shortage impact rating", "Additional commentary"
]

BUG_HEADERS = FIELD_HEADERS + ["Reason"]


async def fetch_data_from_api(context, pack_id: int):
    """
    Fetches shortage start and presumed end dates from the Belgium PharmaStatus API.

    Args:
        context: Playwright browser context (to access request API).
        pack_id (int): The packId to query.

    Returns:
        tuple(str, str): (start_date_str, presumed_end_date_str) in "DD/MM/YYYY" format
    """
    url = "https://pharmastatus.be/api/packs/info/public"
    params = {
        "endRow": 1,
        "language": "en",
        "searchSTR": json.dumps({"packId": pack_id, "ctiExtended": ""}),
        "startRow": 1,
        "version": "7.4.15-hotfix4"
    }

    headers = {
        "Accept": "application/json, text/plain, */*",
        "Accept-Language": "en,en-US;q=0.9",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/122.0.0.0 Safari/537.36"
    }

    try:
        response = await context.request.get(url, params=params, headers=headers)
        if not response.ok:
            print(f"API request failed for packId {pack_id}, status: {response.status}")
            return "", ""

        data = await response.json()
        item = data.get("data", [{}])[0]
        arr = item.get("notARR", [{}])[0]

        start_raw = arr.get("startDate", "")
        end_raw = arr.get("presumedEndDate", "")

        if len(item.get("notARR", [{}])) > 1:
            arr2 = item.get("notARR", [{}])[1]
            if start_raw == "" or start_raw is None:
                start_raw = arr2.get("startDate", "")

            if end_raw == "" or end_raw is None:
                end_raw = arr2.get("presumedEndDate", "")

        fmt = lambda d: datetime.strptime(d[:10], "%Y-%m-%d").strftime("%d/%m/%Y") if d else ""
        return fmt(start_raw), fmt(end_raw)

    except Exception as e:
        print(f"Error fetching dates for packId {pack_id}: {e}")
        return "", ""


def extract_pack_quantity(product_name):
    match = re.search(r'(\d+)\s*x\s*\d+', product_name, re.IGNORECASE)
    if match:
        return int(match.group(1))
    match = re.search(r'(\d+)(?!.*\d)', product_name)
    if match:
        return int(match.group(1))
    return None


def extract_strength(text):
    full_pattern = r'\b\d{1,3}(?:[ .]\d{3})*(?:[.,]?\d+)?\s*(?:mg/ml|mg|µg/dose|IU|%|g/ml|g|ml|µg)(?:/\d+\s*ml)?'
    return re.findall(full_pattern, text, flags=re.IGNORECASE)


async def get_text_by_label(label, page):
    label_el = page.locator(f'xpath=//span[contains(@class,"label") and normalize-space()="{label}"]')
    parent = label_el.locator('xpath=..')
    p = parent.locator('p.ng-binding')
    if await p.count() > 0:
        return await p.inner_text()
    li = parent.locator('li.ng-binding')
    if await li.count() > 0:
        texts = [await li.nth(i).inner_text() for i in range(await li.count())]
        return ";".join(texts)
    span = parent.locator('span.ng-binding')
    if await span.count() > 0:
        texts = [await span.nth(i).inner_text() for i in range(await span.count())]
        return ";".join(texts)
    return None


def format_date(text):
    try:
        parsed = datetime.strptime(text.strip(), "%d-%m-%Y")
        return parsed.strftime("%d/%m/%Y"), parsed
    except ValueError:
        return ""


async def get_alternative_impact_text(page):
    try:
        # This targets the third .col-md-6.medicine-detail-status-value inside the info-end section
        container = page.locator(
            "div.medicine-detail-status-item div.row.info-end div.col-md-6.medicine-detail-status-value").nth(2)
        # This selects the first inner div (e.g., the orange label like "Adaptation of the treatment possible")
        impact_summary = await container.locator("div").nth(0).inner_text()
        return impact_summary
    except Exception as e:
        print(f"Failed to extract impact text: {e}")
    return ""


async def scrape_detail_page(page, detail_url):
    data = {}
    try:
        await page.goto(detail_url)
        await page.wait_for_load_state("networkidle")

        data['Country'] = "Belgium"
        atc4_code = (await get_text_by_label('ATC code', page) or '').split()
        atc4_code = atc4_code[0] if atc4_code else ''
        if atc4_code:
            if len(atc4_code) > 4:
                atc4_code = atc4_code[0:4]
        data['ATC4 code'] = atc4_code
        if atc4_code:
            if len(atc4_code) > 3:
                data['ATC3 code'] = atc4_code[:3]

        active_substance = await get_text_by_label('Active substance', page) or ''
        molecules = [m.strip().split()[0] for m in active_substance.split(';') if m.strip()]
        data['Molecule'] = ";".join(molecules)

        product_name = await page.locator('h1.ng-binding').inner_text()
        data['Product Name'] = product_name
        strength_list = extract_strength(product_name)
        data['Product Strength'] = strength_list[0] if strength_list else ""
        data['Product Pack Size'] = extract_pack_quantity(product_name)
        data['Corporation'] = await get_text_by_label('Company', page)
        data["Relevant unit"] = ""
        data["Shortage Status"] = "Temporarily unavailable"  # Category type will not change
        data["Shortage impact rating"] = ""
        additional_comments = page.locator('div.col-md-6.medicine-detail-status-value div div.ng-binding')
        data[
            'Additional commentary'] = await additional_comments.first.inner_text() if await additional_comments.count() > 0 else ""

        # -- Fetch start & end dates from API --
        pack_id = int(detail_url.split("/")[-1])  # Extract packId from URL
        start_date_str, end_date_str = await fetch_data_from_api(page.context, pack_id)

        # Format start_date_str as datetime to apply comparison
        try:
            start_dt = datetime.strptime(start_date_str, "%d/%m/%Y") if start_date_str else None
        except ValueError:
            start_dt = None

        today = datetime.today()
        today_str = today.strftime("%d/%m/%Y")

        data["Start date"] = start_date_str
        data["End date"] = end_date_str

        if start_dt and start_dt > today:
            data["Date reported"] = today_str  # use today's date
            data["Date last updated"] = start_date_str  # still use future start date
        else:
            data["Date reported"] = start_date_str or today_str
            data["Date last updated"] = start_date_str or today_str

            # Alternative
        data["Alternatives available"] = await get_alternative_impact_text(page)


        return data, None

    except Exception as e:
        return None, str(e)


async def collect_all_ids(page):
    all_ids = []
    while True:
        await page.wait_for_load_state("networkidle")
        rows = page.locator('tr[data-id]')
        for i in range(await rows.count()):
            data_id = await rows.nth(i).get_attribute('data-id')
            if data_id:
                all_ids.append(data_id)

        next_button = page.locator('button.next')
        if await next_button.count() == 0 or await next_button.is_disabled() or not await next_button.is_visible():
            break
        await next_button.click()
        await page.wait_for_timeout(1500)
    return all_ids


async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()
        await page.goto(f"{BASE_URL}/unavailable")
        all_ids = await collect_all_ids(page)
        print(f"Found {len(all_ids)} product IDs")

        detail_page = await browser.new_page()

        good_records = []
        bug_records = []

        for data_id in all_ids:
            detail_url = f"{BASE_URL}/{data_id}"
            product_data, error = await scrape_detail_page(detail_page, detail_url)

            if error:
                bug_row = {field: "" for field in FIELD_HEADERS}
                bug_row["Reason"] = f"Scrape error: {error}"
                bug_records.append(bug_row)
                continue

            missing_fields = [field for field in ["ATC3 code", "ATC4 code", "Molecule", "Product Name"]
                              if not product_data.get(field)]
            if missing_fields:
                bug_row = {field: product_data.get(field, "") for field in FIELD_HEADERS}
                bug_row["Reason"] = f"Missing fields: {', '.join(missing_fields)}"
                bug_records.append(bug_row)
                continue

            print(product_data)

            good_records.append(product_data)

        await browser.close()

        # Create output folder
        os.makedirs(FOLDER_PATH, exist_ok=True)

        # Save good records
        if good_records:
            df_good = pd.DataFrame(good_records)
            df_good = df_good[[col for col in FIELD_HEADERS if col in df_good.columns]]
            df_good.to_excel(LL_FILENAME, index=False, engine="openpyxl")
            df_good.to_excel(EN_FILENAME, index=False, engine="openpyxl")
            print(f"Saved {len(df_good)} good records to:\n- {LL_FILENAME}\n- {EN_FILENAME}")

        # Save bug records
        if bug_records:
            df_bug = pd.DataFrame(bug_records)
            df_bug = df_bug[[col for col in BUG_HEADERS if col in df_bug.columns]]
            df_bug.to_excel(BUGS_FILENAME, index=False, engine="openpyxl")
            print(f"Saved {len(df_bug)} bug records to: {BUGS_FILENAME}")


if __name__ == "__main__":
    asyncio.run(main())

