# -*- coding: utf-8 -*-
"""finland_scraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BZdX1qUE2Z6YV2vCL_Vhnrdu9Zbt8lXV
"""

import requests, os
import pandas as pd
import time
import random
from datetime import datetime
from openpyxl import load_workbook, Workbook

def convert_date_format(date_str):
    if date_str:
        dt = datetime.strptime(date_str, "%d.%m.%Y")
        return dt.strftime("%d/%m/%Y")
    return date_str

def fetch_fimea_data():
    base_url = "https://fimea.fi/en/databases_and_registers/shortages"
    api_endpoint = "https://fimea.fi/en/databases_and_registers/shortages"

    # Parameters from the working request
    params_template = {
        "p_p_id": "fi_yja_fimea_med_web_AvailabilityFailurePortlet_INSTANCE_4yKNiY00xuDZ",
        "p_p_lifecycle": "2",
        "p_p_state": "normal",
        "p_p_mode": "view",
        "p_p_resource_id": "/saatavuushairio/search",
        "p_p_cacheability": "cacheLevelPage",
        "search": "",
        "order[0][column]": "0",
        "order[0][dir]": "desc",
        "draw": "1",
        "startDate": "",
        "endDate": ""
    }

    # Headers from the working request
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36",
        "Accept": "application/json, text/javascript, */*; q=0.01",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "en-US,en;q=0.9",
        "Priority": "u=1, i",
        "Referer": base_url,
        "Sec-Ch-Ua": '"Google Chrome";v="137", "Chromium";v="137", "Not/A)Brand";v="24"',
        "Sec-Ch-Ua-Arch": '"x86"',
        "Sec-Ch-Ua-Bitness": '"64"',
        "Sec-Ch-Ua-Full-Version": '"137.0.7151.104"',
        "Sec-Ch-Ua-Mobile": "?0",
        "Sec-Ch-Ua-Platform": '"Windows"',
        "Sec-Ch-Ua-Platform-Version": '"10.0.0"',
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-origin",
        "X-Requested-With": "XMLHttpRequest"
    }

    all_records = []  # Will store dictionaries instead of raw data
    start = 0
    length = 100  # Number of records per request
    session = requests.Session()

    # Field mapping configuration
    field_mapping = [
        "Date Fetched",
        "Product Name",
        "Product Strength",
        "Form",
        "Product Pack Size",
        "ATC4 code",
        "Molecule",
        "Corporation",
        "Start date",
        "End date",
        "Additional commentary",
        "Date reported",
        "Critical Shortage",
        "Vnr",
        "Medicine Type",
        "Parallel Import"
    ]

    # Initial request to set cookies
    print("Establishing session...")
    session.get(base_url, headers=headers)

    while True:
        # Create fresh params with cache-busting timestamp
        params = params_template.copy()
        params.update({
            "start": str(start),
            "length": str(length),
            "_": str(int(time.time() * 1000))  # Cache-buster timestamp
        })

        print(f"Fetching records {start} to {start+length}...")

        try:
            response = session.get(
                api_endpoint,
                params=params,
                headers=headers,
                timeout=30
            )

            # Check for valid JSON response
            if 'application/json' not in response.headers.get('Content-Type', ''):
                print(f"Unexpected content type: {response.headers.get('Content-Type')}")
                print(f"Response preview: {response.text[:300]}")
                break

            data = response.json()
            records = data.get("data", [])

            if not records:
                print("No more records found")
                break

            # Process each record into a dictionary with named fields
            for record in records:
                # Create dictionary from field mapping and record values
                record_dict = {}
                for i, value in enumerate(record):
                    if i < len(field_mapping):
                        field_name = field_mapping[i]
                        record_dict[field_name] = value

                # Add custom fields (like Country)
                record_dict["Country"] = "Finland"
                atc3Code = record_dict["ATC4 code"]

                record_dict["ATC3 code"] = ""
                if atc3Code:
                  if len(atc3Code) > 3:
                    record_dict["ATC3 code"] = atc3Code[:3]

                if record_dict["ATC4 code"]:
                  if len(record_dict["ATC4 code"]) > 4:
                    record_dict["ATC4 code"] = record_dict["ATC4 code"][:4]

                record_dict["Shortage impact rating"] = ""
                record_dict["Relevant unit number"] = ""
                record_dict["Alternatives available"] = ""

                # Get today's date
                today_dt = datetime.today().strftime("%d/%m/%Y")

                # Correcting date format
                start_date = convert_date_format(record_dict["Start date"])
                record_dict["Start date"] = start_date
                end_date = convert_date_format(record_dict["End date"])
                record_dict["End date"] = end_date
                record_dict["Date reported"] = convert_date_format(record_dict["Date reported"])

                if start_date>today_dt:
                  record_dict["Date last updated"] = today_dt
                else:
                  record_dict["Date last updated"] = start_date

                if end_date>today_dt:
                  record_dict["Shortage Status"] = "Shortage ongoing"
                else:
                  record_dict["Shortage Status"] = "Shortage ended"

                #removing extra data
                del record_dict["Date Fetched"]
                del record_dict["Form"]
                del record_dict["Vnr"]
                del record_dict["Medicine Type"]
                # del record_dict["End date"]
                del record_dict["Parallel Import"]

                all_records.append(record_dict)

            total_records = data.get("recordsTotal", 0)

            if len(all_records) >= total_records:
                print(f"Finished fetching {len(all_records)} records")
                break

            start += length
            time.sleep(random.uniform(1.5, 3.0))  # Random delay to avoid detection

        except Exception as e:
            print(f"Request failed: {str(e)}")
            if 'response' in locals():
                print(f"Status code: {response.status_code}")
                print(f"Response text: {response.text[:500]}")
            break

    return all_records


def save_to_xlsx(records, filename, isBug):
    if not records:
        return

    df = pd.DataFrame(records)

    # Desired column order
    column_order = [
        "Country", "ATC3 code", "ATC4 code", "Molecule",
        "Product Name", "Product Strength", "Product Pack Size", "Corporation", "Shortage Status",
        "Date reported", "Start date", "End date",
        "Date last updated", "Relevant unit number",
        "Alternatives available", "Shortage impact rating", "Additional commentary"
    ]

    if isBug:
        column_order.append("Reason")

    # Reorder columns
    df = df[[col for col in column_order if col in df.columns]]

    # Ensure the folder exists
    os.makedirs(os.path.dirname(filename), exist_ok=True)

    # Save Excel file (overwrite every time)
    df.to_excel(filename, index=False, engine="openpyxl")
    print(f"Saved file: {filename} with {len(df)} records")



if __name__ == "__main__":
    print("Starting FIMEA data extraction...")
    records = fetch_fimea_data()

    today = datetime.now().strftime("%Y%m%d")
    folder_path = r"C:\Users\curra\OneDrive\Desktop\Personal\PS\Data\Finland"
    #folder_path = os.getcwd()
    ll_filename = os.path.join(folder_path, f"Finland Output LL {today}.xlsx")
    en_filename = os.path.join(folder_path, f"Finland Output EN {today}.xlsx")
    bugs_filename = os.path.join(folder_path, f"Finland Bugs {today}.xlsx")


    bug_records = []
    good_records = []
    for record in records:
        atc_code = record.get("ATC4 code", "").strip()
        if not atc_code:
            bug = record.copy()
            bug["Reason"] = "Missing ATC3 and ATC4 code"
            bug_records.append(bug)
        elif not record["Product Name"]:
            bug = record.copy()
            bug["Reason"] = "Missing product name"
            bug_records.append(bug)
        elif not record["Molecule"]:
            bug = record.copy()
            bug["Reason"] = "Missing molecule name"
            bug_records.append(bug)
        else:
            good_records.append(record)

    save_to_xlsx(good_records, ll_filename, False)
    save_to_xlsx(good_records, en_filename, False)
    save_to_xlsx(bug_records, bugs_filename, True)
    print("Process completed")

