# -*- coding: utf-8 -*-
"""netherland_scraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ol0KULvvJJ1SmT4RZ-KTL1RhUNWvE60B
"""

import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
from datetime import datetime, timedelta
import csv
import os
import re
import copy
import pandas as pd
from deepl import Translator

from dotenv import load_dotenv


# Initialize DeepL Pro API with proper configuration
def initialize_deepl_pro():
    """Initialize DeepL Pro API with enhanced configuration"""
    try:
        # Load API key directly from file (no .env parsing needed)
        api_key_path = r"C:\Users\curra\OneDrive\Desktop\Personal\PS\Data\DeepL API Key May2025.env"

        # Read API key directly (raw string without .env parsing)
        with open(api_key_path, 'r') as f:
            DEEPL_API_KEY = f.read().strip()

        # Configure Pro API with proper options
        translator = Translator(
            DEEPL_API_KEY,
            server_url="https://api.deepl.com",  # Pro API endpoint
            send_platform_info=False,  # Disable telemetry
        )

        # Verify connection
        usage = translator.get_usage()
        if usage.character.limit == 0:
            raise Exception("Pro API not properly activated")

        return translator

    except Exception as e:
        print(f"⚠️ DeepL Pro API initialization failed: {str(e)}")
        return None


# === Helper Functions ===
def load_translation_master():
    """Load translation master Excel file into DataFrames"""
    translation_path = r"C:\Users\curra\OneDrive\Desktop\Personal\PS\Data\PS Translation master v1.xlsx"
    return {
        "Molecule": pd.read_excel(translation_path, sheet_name="Molecule"),
        "Product Name": pd.read_excel(translation_path, sheet_name="Product Name"),
        "Product Strength": pd.read_excel(translation_path, sheet_name="Product Strength"),
        "Product Pack Size": pd.read_excel(translation_path, sheet_name="Product Pack Size"),
        "Additional Commentary": pd.read_excel(translation_path, sheet_name="Additional Commentary")
    }


def load_atc_mapping():
    """Load ATC mapping Excel file"""
    atc_path = r"C:\Users\curra\OneDrive\Desktop\Personal\PS\Data\Master ATC mapping.xlsx"
    return pd.read_excel(atc_path)


def load_shortage_status_mapping():
    """Load shortage status mapping Excel file"""
    status_path = r"C:\Users\curra\OneDrive\Desktop\Personal\PS\Data\Shortage Status Master.xlsx"
    return pd.read_excel(status_path)


def translate_text(text, category, translation_master, country="Netherlands"):
    """Translate text using translation master or DeepL API"""
    if not text or pd.isna(text):
        return ""

    # Try translation master first
    df = translation_master[category]
    match = df[(df["Country"] == country) & (df["Untranslated"] == text)]
    if not match.empty:
        return match.iloc[0]["Translated"]

    # Fallback to DeepL API
    try:
        deeL = initialize_deepl_pro()
        result = deeL.translate_text(text, target_lang="EN-GB")
        return result.text
    except Exception as e:
        print(f"DeepL translation failed for '{text}': {str(e)}")
        return text


def get_atc_codes(molecule_en, atc_mapping):
    """Get ATC codes from English molecule name"""
    if not molecule_en or pd.isna(molecule_en):
        return ("", "")

    match = atc_mapping[atc_mapping["Molecule (English)"] == molecule_en]
    if not match.empty:
        atc4 = match.iloc[0]["ATC4 code"]
        atc3 = atc4[:4] if len(atc4) >= 4 else ""
        return (atc3, atc4)
    return ("", "")


def translate_shortage_status(status_nl, status_mapping):
    """Translate shortage status using mapping file"""
    if not status_nl or pd.isna(status_nl):
        return status_nl

    match = status_mapping[status_mapping["Original"] == status_nl]
    if not match.empty:
        return match.iloc[0]["Translated"]
    return status_nl


def parse_end_date(date_str):
    """Parse various end date formats including quarters, Dutch phrases, and normal dates"""
    if not date_str or not isinstance(date_str, str):
        return date_str

    date_str = date_str.strip().lower()

    # Handle special Dutch phrases
    if any(phrase in date_str for phrase in ["uit de handel", "product niet actief", "onbekend"]):
        return date_str  # "Discontinued"

        # First check for the special "áµ‰" character case
    if "áµ‰" in date_str:
        try:
            # Extract quarter and year from formats like "3áµ‰ kwartaal 2025"
            parts = date_str.split()
            quarter = int(parts[0].replace("áµ‰", ""))
            year = parts[2]

            quarter_dates = {
                1: "15/02/",  # Q1: February 15
                2: "15/05/",  # Q2: May 15
                3: "15/08/",  # Q3: August 15
                4: "15/11/"  # Q4: November 15
            }

            if quarter in quarter_dates:
                return f"{quarter_dates[quarter]}{year}"
        except:
            pass

    # Handle other quarter formats (3e kwartaal 2025, 3ème kwartaal 2025)
    quarter_match = re.match(r'(\d+)(?:e|è|me?)?\s*kwartaal\s*(\d{4})', date_str)
    if quarter_match:
        quarter = int(quarter_match.group(1))
        year = int(quarter_match.group(2))

        quarter_dates = {
            1: "15/02/",  # Q1: February 15
            2: "15/05/",  # Q2: May 15
            3: "15/08/",  # Q3: August 15
            4: "15/11/"  # Q4: November 15
        }

        if quarter in quarter_dates:
            return f"{quarter_dates[quarter]}{year}"
        return f"Q{quarter} {year}"

    # Handle week numbers (week 40 2025)
    week_match = re.match(r'week\s*(\d+)\s*(\d{4})', date_str)
    if week_match:
        week_num = int(week_match.group(1))
        year = int(week_match.group(2))
        try:
            # Get the Monday of the given week and add 3 days to get Thursday (mid-week)
            date = datetime.strptime(f"{year}-W{week_num - 1}-1", "%Y-W%W-%w") + timedelta(days=3)
            return date.strftime("%d/%m/%Y")
        except:
            return f"Week {week_num} {year}"

    # Handle Dutch months (maart 2026)
    month_map = {
        'januari': '01', 'februari': '02', 'maart': '03', 'april': '04',
        'mei': '05', 'juni': '06', 'juli': '07', 'augustus': '08',
        'september': '09', 'oktober': '10', 'november': '11', 'december': '12'
    }

    for month_name, month_num in month_map.items():
        if month_name in date_str:
            year_match = re.search(r'\d{4}', date_str)
            year = year_match.group(0) if year_match else datetime.now().year
            return f"15/{month_num}/{year}"  # Mid-month date

    # Handle standard date formats (DD/MM/YYYY)
    date_match = re.match(r'(\d{2})/(\d{2})/(\d{4})', date_str)
    if date_match:
        day, month, year = date_match.groups()
        try:
            datetime.strptime(f"{day}/{month}/{year}", "%d/%m/%Y")
            return f"{day}/{month}/{year}"
        except ValueError:
            pass

    # Handle year only (2025)
    if re.match(r'^\d{4}$', date_str):
        return f"01/07/{date_str}"  # Mid-year: July 1st

    split_list = date_str.split()
    if len(split_list) == 2:
        if split_list[0] in month_map:
            _month = month_map[split_list[0]]
            return f"15/{_month}/{split_list[0]}"

    if "áµ‰ kwartaal" in date_str or "áµ kwartaal" in date_str or ("aµ" in date_str and "kwartaal" in date_str):
        try:
            _quarter_year = date_str.split()
            quarter_dates = {
                1: "15/02/",  # Q1: February 15
                2: "15/05/",  # Q2: May 15
                3: "15/08/",  # Q3: August 15
                4: "15/11/"  # Q4: November 15
            }
            return f"{quarter_dates[int(date_str[0])]}{_quarter_year[2]}"
        except ValueError:
            pass

    if "kwartaal" in date_str:
        try:
            _quarter_year = date_str.split()
            quarter_dates = {
                1: "15/02/",  # Q1: February 15
                2: "15/05/",  # Q2: May 15
                3: "15/08/",  # Q3: August 15
                4: "15/11/"  # Q4: November 15
            }
            return f"{quarter_dates[int(date_str[0])]}{_quarter_year[2]}"
        except ValueError:
            pass

    return date_str  # Default for unparseable dates


def parse_main_date(date_str):
    """Parse dates from the main page with Dutch month abbreviations"""
    if not date_str:
        return ""

    month_map = {
        'jan': 1, 'feb': 2, 'mrt': 3, 'apr': 4, 'mei': 5, 'jun': 6,
        'jul': 7, 'aug': 8, 'sep': 9, 'okt': 10, 'nov': 11, 'dec': 12
    }

    parts = date_str.split()
    if len(parts) == 3:
        day = parts[0].zfill(2)
        month_str = parts[1].replace('.', '').lower()[:3]
        year = parts[2]
        if month_str in month_map:
            return f"{day}/{month_map[month_str]:02d}/{year}"

    return date_str


def write_output_file(data, filename, fieldnames, is_bugs_file=False, bug_reasons=None):
    """
    Enhanced CSV writer with bug reporting capabilities
    Args:
        data: List of dictionaries containing row data
        filename: Output file path
        fieldnames: List of column headers
        is_bugs_file: Whether this is a bug report file
        bug_reasons: Dictionary mapping row indices to reason strings
    """
    try:
        file_exists = os.path.exists(filename)

        # Add 'Reason' column for bug files if not present
        if is_bugs_file and 'Reason' not in fieldnames:
            fieldnames = fieldnames.copy()  # Avoid modifying original
            fieldnames.append('Reason')

        with open(filename, mode="a" if file_exists else "w", newline="", encoding="utf-8", errors='replace') as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)

            if not file_exists:
                writer.writeheader()

            for idx, row in enumerate(data):
                if is_bugs_file and isinstance(bug_reasons, dict) and idx in bug_reasons:
                    row['Reason'] = bug_reasons[idx]
                writer.writerow(row)

    except Exception as e:
        print(f"⚠️ Failed to write {filename}: {str(e)}")



def main():
    # Load all mapping files
    # translation_master = load_translation_master()
    # atc_mapping = load_atc_mapping()
    # status_mapping = load_shortage_status_mapping()

    base_url = "https://farmanco.knmp.nl/"
    session = requests.Session()
    session.headers.update({"User-Agent": "Mozilla/5.0"})

    # Prepare output file
    today = datetime.now().strftime("%Y%m%d")


    # Fix environment path handling
    #folder_path = r"C:\Users\curra\OneDrive\Desktop\Personal\PS\Data\Netherlands"
    ll_filename = f"Netherlands Output LL {today}.csv"
    #en_filename = f"Netherlands Output EN {today}.csv"
    bugs_filename = f"Netherlands Bugs {today}.csv"

    print("Fetching main page...")
    response = session.get(base_url)
    response.raise_for_status()
    soup = BeautifulSoup(response.text, "html.parser")

    links = soup.find_all("a", class_="shortage-flex-table")
    print(f"Found {len(links)} products")

    today = datetime.now().strftime("%Y%m%d")
    fieldnames = [
        "Country", "ATC3 code", "ATC4 code", "Molecule", "Product Name",
        "Product Strength", "Product Pack Size", "Corporation", "Shortage Status",
        "Date reported", "Start date", "End date", "Date last updated",
        "Relevant unit number", "Alternatives available", "Shortage impact rating",
        "Additional commentary"
    ]

    bug_reasons_dict = {}
    ll_data = []
    en_data = []
    bugs_data = []

    for a_tag in links:
        base_dict = {
            "Country": "Netherlands",
            "Relevant unit number": "",
            "Alternatives available": "",
            "ATC3 code": "",
            "ATC4 code": "",
        }

        # Extract main page data
        base_dict["Molecule"] = a_tag.find("li", class_="sort-active-ingredient").get_text(strip=True) if a_tag.find(
            "li", class_="sort-active-ingredient") else ""
        impact = a_tag.find("li", class_="sort-preferential").get_text(strip=True) if a_tag.find("li",
                                                                                                 class_="sort-preferential") else ""
        base_dict["Shortage impact rating"] = "High" if impact == "Ja" else ""

        date_str = a_tag.find("li", class_="sort-date active").get_text(strip=True) if a_tag.find("li",
                                                                                                  class_="sort-date active") else ""
        base_dict["Start date"] = parse_main_date(date_str)
        base_dict["Date last updated"] = base_dict["Start date"]

        # Process detail page
        detail_url = urljoin(base_url, a_tag.get("href"))
        # print(f"Processing: {detail_url}")
        try:
            detail_response = session.get(detail_url)
            detail_response.raise_for_status()
            detail_soup = BeautifulSoup(detail_response.text, "html.parser")

            for entry in detail_soup.find_all("div", class_="expandable mainlevel shortage public"):
                product_dict = copy.deepcopy(base_dict)
                items = entry.select(".expandable-header .item")

                if items:
                    product_dict.update({
                        "Product Name": items[0].get_text(strip=True) if len(items) > 0 else "",
                        "Corporation": items[1].get_text(strip=True) if len(items) > 1 else "",
                        "Product Pack Size": items[2].get_text(strip=True) if len(items) > 2 else "",
                        "Shortage Status": items[3].get_text(strip=True) if len(items) > 3 else ""
                    })

                # Handle end date
                expected_date = entry.select_one(".expandable-header .date .value")
                end_date_str = expected_date.get_text(strip=True) if expected_date else ""
                product_dict["End date"] = parse_end_date(end_date_str)

                # Additional fields
                h3 = entry.find_previous("h3", class_="tocEntry")
                product_dict["Product Strength"] = h3.get_text(strip=True) if h3 else ""

                shortage_reason = entry.select_one("div.wrapper.flex p")
                product_dict["Additional commentary"] = shortage_reason.get_text(strip=True) if shortage_reason else ""

                # Set Date Reported
                today_date = datetime.now().date()

                # Use Date last updated if available and in the past
                if product_dict["Date last updated"]:
                    try:
                        # Parse the date in DD/MM/YYYY format
                        last_updated = datetime.strptime(product_dict["Date last updated"], "%d/%m/%Y").date()

                        # Only use it if it's today or in the past
                        if last_updated <= today_date:
                            product_dict["Date reported"] = product_dict["Date last updated"]
                        else:
                            # If it's in the future, use today's date
                            product_dict["Date reported"] = today_date.strftime("%d/%m/%Y")
                    except ValueError:
                        # If parsing fails, use today's date
                        product_dict["Date reported"] = today_date.strftime("%d/%m/%Y")
                else:
                    # If no last updated date, use today's date
                    product_dict["Date reported"] = today_date.strftime("%d/%m/%Y")

                ll_data.append(product_dict)

                # Create English version
                # en_dictionary = copy.deepcopy(product_dict)
                # # Translate fields
                # en_dictionary["Molecule"] = translate_text(en_dictionary["Molecule"], "Molecule", translation_master)
                # en_dictionary["Product Name"] = translate_text(en_dictionary["Product Name"], "Product Name",
                #                                                translation_master)
                # en_dictionary["Product Strength"] = translate_text(en_dictionary["Product Strength"], "Product Strength",
                #                                                    translation_master)
                # en_dictionary["Product Pack Size"] = translate_text(en_dictionary["Product Pack Size"],
                #                                                     "Product Pack Size", translation_master)
                # en_dictionary["Additional commentary"] = translate_text(en_dictionary["Additional commentary"],
                #                                                         "Additional Commentary", translation_master)
                # en_dictionary["Shortage Status"] = translate_shortage_status(en_dictionary["Shortage Status"],
                #                                                              status_mapping)

                # # Get ATC codes
                # atc3, atc4 = get_atc_codes(en_dictionary["Molecule"], atc_mapping)
                # en_dictionary["ATC3 code"] = atc3
                # en_dictionary["ATC4 code"] = atc4

                # if not atc3 or not atc4:
                #     bug_entry = copy.deepcopy(en_dictionary)
                #     bug_reason = (
                #         "Missing ATC3 & ATC4 code mapping" if not atc3 and not atc4 else
                #         "Missing ATC3 code mapping" if not atc3 else
                #         "Missing ATC4 code mapping"
                #     )
                #     bug_reasons_dict[len(bugs_data)] = bug_reason  # ← index matches current length
                #     bugs_data.append(bug_entry)

                # en_data.append(en_dictionary)

        except Exception as e:
            print(f"Error processing {detail_url}: {str(e)}")

    write_output_file(ll_data, ll_filename, fieldnames, is_bugs_file=False)
    # write_output_file(en_data, en_filename, fieldnames, is_bugs_file=False)
    if bugs_data:
        write_output_file(bugs_data, bugs_filename, fieldnames, True, bug_reasons_dict)
        print(f"⚠️ Data saved to {bugs_filename}")

    print(f"✅ Data saved to {ll_filename}")
    #print(f"✅ Data saved to {en_filename}")


if __name__ == "__main__":
  main()

# Commented out IPython magic to ensure Python compatibility.
# %pip install python-dotenv

# Commented out IPython magic to ensure Python compatibility.
# %pip install deepl


